import type {
  ActivityItem,
  AlertItem,
  Baseline,
  DiffResult,
  Endpoint,
  ScheduleItem,
  WorkspaceStats,
} from "./types";

export const workspaceStats: WorkspaceStats = {
  healthy: 12,
  breaking: 2,
  warnings: 3,
  checksToday: 47,
  endpoints: 17,
  baselines: 34,
};

export const endpoints: Endpoint[] = [
  {
    id: "ep_users",
    name: "List Users",
    url: "https://api.acme.dev/v1/users",
    method: "GET",
    environment: "production",
    tags: ["users", "core"],
    description: "Paginated user directory used by the dashboard and mobile apps.",
    health: "breaking",
    authType: "bearer",
    lastCheckedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    responseTime: 184,
    baselineVersion: 4,
    breakingCount: 2,
    warningCount: 1,
  },
  {
    id: "ep_orders",
    name: "Create Order",
    url: "https://api.acme.dev/v1/orders",
    method: "POST",
    environment: "production",
    tags: ["orders", "payments"],
    description: "Primary checkout mutation for web and partner integrations.",
    health: "warning",
    authType: "api_key",
    lastCheckedAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    responseTime: 312,
    baselineVersion: 7,
    breakingCount: 0,
    warningCount: 2,
  },
  {
    id: "ep_products",
    name: "Get Product",
    url: "https://api.acme.dev/v1/products/:id",
    method: "GET",
    environment: "production",
    tags: ["catalog"],
    health: "healthy",
    authType: "none",
    lastCheckedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    responseTime: 92,
    baselineVersion: 3,
  },
  {
    id: "ep_webhooks",
    name: "Webhook Delivery",
    url: "https://api.acme.dev/v1/webhooks/deliveries",
    method: "GET",
    environment: "staging",
    tags: ["webhooks", "internal"],
    health: "healthy",
    authType: "bearer",
    lastCheckedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    responseTime: 156,
    baselineVersion: 2,
  },
  {
    id: "ep_auth",
    name: "Token Refresh",
    url: "https://api.acme.dev/v1/auth/refresh",
    method: "POST",
    environment: "production",
    tags: ["auth"],
    health: "healthy",
    authType: "bearer",
    lastCheckedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    responseTime: 67,
    baselineVersion: 5,
  },
  {
    id: "ep_invoice",
    name: "Get Invoice",
    url: "https://api.acme.dev/v1/invoices/:id",
    method: "GET",
    environment: "production",
    tags: ["billing"],
    health: "breaking",
    authType: "bearer",
    lastCheckedAt: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    responseTime: 241,
    baselineVersion: 6,
    breakingCount: 1,
    warningCount: 0,
  },
  {
    id: "ep_search",
    name: "Search Catalog",
    url: "https://api.acme.dev/v1/search",
    method: "GET",
    environment: "production",
    tags: ["search", "catalog"],
    health: "warning",
    authType: "api_key",
    lastCheckedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    responseTime: 428,
    baselineVersion: 1,
    warningCount: 1,
  },
  {
    id: "ep_health",
    name: "Health Check",
    url: "https://api.acme.dev/health",
    method: "GET",
    environment: "production",
    tags: ["ops"],
    health: "healthy",
    authType: "none",
    lastCheckedAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    responseTime: 18,
    baselineVersion: 1,
  },
];

export const baselineBody = {
  data: {
    id: "usr_8f2a1c",
    email: "alex@acme.dev",
    name: "Alex Rivera",
    role: "admin",
    created_at: "2025-11-02T14:22:01Z",
    profile: {
      avatar_url: "https://cdn.acme.dev/a.png",
      timezone: "America/New_York",
      preferences: {
        theme: "dark",
        notifications: true,
      },
    },
    permissions: ["read", "write", "billing"],
    meta: {
      request_id: "req_abc123",
      version: "2024-06-01",
    },
  },
  pagination: {
    page: 1,
    per_page: 20,
    total: 148,
  },
};

export const currentBody = {
  data: {
    id: "usr_8f2a1c",
    email: "alex@acme.dev",
    full_name: "Alex Rivera",
    role: "admin",
    created_at: "2025-11-02T14:22:01Z",
    profile: {
      avatar_url: "https://cdn.acme.dev/a.png",
      timezone: "America/Los_Angeles",
      preferences: {
        theme: "system",
        notifications: true,
        digest: "weekly",
      },
    },
    permissions: ["read", "write", "billing", "admin"],
    meta: {
      request_id: "req_xyz789",
      version: "2025-01-15",
      schema: "v2",
    },
  },
  pagination: {
    page: 1,
    per_page: 25,
    total: 148,
    has_more: false,
  },
};

export const baselines: Baseline[] = [
  {
    id: "bl_4",
    version: 4,
    statusCode: 200,
    headers: {
      "content-type": "application/json",
      "x-request-id": "req_abc123",
      "cache-control": "private, max-age=60",
    },
    body: baselineBody,
    responseTime: 176,
    contentSize: 482,
    notes: "Approved after permissions array expansion.",
    approved: true,
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    endpointId: "ep_users",
  },
  {
    id: "bl_3",
    version: 3,
    statusCode: 200,
    headers: {
      "content-type": "application/json",
      "x-request-id": "req_old",
    },
    body: {
      ...baselineBody,
      data: { ...baselineBody.data, permissions: ["read", "write"] },
    },
    responseTime: 162,
    contentSize: 450,
    approved: true,
    isActive: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
    endpointId: "ep_users",
  },
  {
    id: "bl_2",
    version: 2,
    statusCode: 200,
    headers: { "content-type": "application/json" },
    body: baselineBody,
    responseTime: 198,
    contentSize: 440,
    approved: true,
    isActive: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    endpointId: "ep_users",
  },
];

export const sampleDiff: DiffResult = {
  id: "diff_users_latest",
  endpointId: "ep_users",
  endpointName: "List Users",
  createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  breakingCount: 2,
  warningCount: 1,
  infoCount: 4,
  accepted: false,
  baseline: {
    version: 4,
    statusCode: 200,
    body: baselineBody,
    responseTime: 176,
    contentSize: 482,
  },
  current: {
    statusCode: 200,
    body: currentBody,
    responseTime: 184,
    contentSize: 528,
  },
  changes: [
    {
      id: "c1",
      path: "data.name",
      type: "removed",
      severity: "breaking",
      oldValue: "Alex Rivera",
      message: "Field removed — clients reading data.name will break",
    },
    {
      id: "c2",
      path: "data.full_name",
      type: "added",
      severity: "info",
      newValue: "Alex Rivera",
      message: "New field added",
    },
    {
      id: "c3",
      path: "pagination.per_page",
      type: "changed",
      severity: "breaking",
      oldValue: 20,
      newValue: 25,
      message: "Default page size changed from 20 to 25",
    },
    {
      id: "c4",
      path: "data.profile.timezone",
      type: "changed",
      severity: "warning",
      oldValue: "America/New_York",
      newValue: "America/Los_Angeles",
      message: "Timezone value changed",
    },
    {
      id: "c5",
      path: "data.profile.preferences.digest",
      type: "added",
      severity: "info",
      newValue: "weekly",
      message: "New nested preference field",
    },
    {
      id: "c6",
      path: "data.permissions[3]",
      type: "added",
      severity: "info",
      newValue: "admin",
      message: "Array element added",
    },
    {
      id: "c7",
      path: "pagination.has_more",
      type: "added",
      severity: "info",
      newValue: false,
      message: "New pagination flag",
    },
    {
      id: "c8",
      path: "data.meta.schema",
      type: "added",
      severity: "warning",
      newValue: "v2",
      message: "Schema version marker introduced",
    },
  ],
};

export const activities: ActivityItem[] = [
  {
    id: "a1",
    type: "diff_detected",
    title: "Breaking changes on List Users",
    description: "2 breaking · 1 warning · baseline v4",
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    href: "/diff/diff_users_latest",
  },
  {
    id: "a2",
    type: "alert_sent",
    title: "Slack alert delivered",
    description: "#api-alerts · Get Invoice status drift",
    createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: "a3",
    type: "check_run",
    title: "Scheduled check completed",
    description: "Create Order · 312ms · 2 warnings",
    createdAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    href: "/endpoints/ep_orders",
  },
  {
    id: "a4",
    type: "baseline_accepted",
    title: "Baseline v5 approved",
    description: "Token Refresh · by you",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "a5",
    type: "endpoint_added",
    title: "Endpoint added",
    description: "Search Catalog · production",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    href: "/endpoints/ep_search",
  },
  {
    id: "a6",
    type: "baseline_created",
    title: "Baseline captured",
    description: "Health Check · v1",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: "a7",
    type: "member_invited",
    title: "Member invited",
    description: "jordan@acme.dev · Member",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const alerts: AlertItem[] = [
  {
    id: "al1",
    channel: "slack",
    severity: "breaking",
    message: "List Users — field data.name removed",
    status: "sent",
    endpointName: "List Users",
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    sentAt: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
  },
  {
    id: "al2",
    channel: "email",
    severity: "breaking",
    message: "Get Invoice — status code 200 → 404",
    status: "sent",
    endpointName: "Get Invoice",
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    sentAt: new Date(Date.now() - 1000 * 60 * 19).toISOString(),
  },
  {
    id: "al3",
    channel: "discord",
    severity: "warning",
    message: "Create Order — response time +48%",
    status: "sent",
    endpointName: "Create Order",
    createdAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    sentAt: new Date(Date.now() - 1000 * 60 * 39).toISOString(),
  },
  {
    id: "al4",
    channel: "webhook",
    severity: "warning",
    message: "Search Catalog — latency regression",
    status: "failed",
    endpointName: "Search Catalog",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "al5",
    channel: "slack",
    severity: "info",
    message: "Token Refresh — schema field meta.schema added",
    status: "sent",
    endpointName: "Token Refresh",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    sentAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
];

export const schedules: ScheduleItem[] = [
  {
    id: "sch1",
    endpointId: "ep_users",
    endpointName: "List Users",
    frequency: "hourly",
    enabled: true,
    lastRunAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    nextRunAt: new Date(Date.now() + 1000 * 60 * 48).toISOString(),
  },
  {
    id: "sch2",
    endpointId: "ep_orders",
    endpointName: "Create Order",
    frequency: "hourly",
    enabled: true,
    lastRunAt: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    nextRunAt: new Date(Date.now() + 1000 * 60 * 32).toISOString(),
  },
  {
    id: "sch3",
    endpointId: "ep_invoice",
    endpointName: "Get Invoice",
    frequency: "daily",
    enabled: true,
    lastRunAt: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    nextRunAt: new Date(Date.now() + 1000 * 60 * 60 * 21).toISOString(),
  },
  {
    id: "sch4",
    endpointId: "ep_search",
    endpointName: "Search Catalog",
    frequency: "daily",
    enabled: false,
    lastRunAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "sch5",
    endpointId: "ep_health",
    endpointName: "Health Check",
    frequency: "hourly",
    enabled: true,
    lastRunAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    nextRunAt: new Date(Date.now() + 1000 * 60 * 58).toISOString(),
  },
];

export function getEndpoint(id: string) {
  return endpoints.find((e) => e.id === id);
}

export function getDiff(id: string) {
  if (id === sampleDiff.id || id === "latest") return sampleDiff;
  return sampleDiff;
}
